apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  resources:
  - name: source
    type: git
  tasks:
  - name: echo-message
    taskRef:
      name: test-task
    resources:
      inputs:
      - name: source
        resource: source
