kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: commit-status-tracker
subjects:
- kind: ServiceAccount
  name: commit-status-tracker
roleRef:
  kind: Role
  name: commit-status-tracker
  apiGroup: rbac.authorization.k8s.io
